<?php include __DIR__ . '/../header.html' ?>
	<div class="container">
		<div class="row">
			<h3>Adicionar categorias</h3>
			<h5><?php echo "Post - {$post->getTitulo()}"; ?></h5>
			<form name="form" method="post" action="<?php echo "/posts/{$post->getId()}/set-categories"; ?>">
				<div class="form-group">
					<label for="categories">Categorias</label>
					<select class="form-control" name="categories[]" multiple>
						<?php foreach ($categories as $category): ?>
							<option value="<?php echo $category->getId(); ?>"><?php echo $category->getNome(); ?></option>
						<?php endforeach; ?>
					</select>
				</div>
				<button type="submit" class="btn btn-default">Enviar</button>
			</form>
		</div>
	</div>
<?php include __DIR__ . '/../footer.html' ?>
