<?php include __DIR__ . '/../header.html' ?>
	<div class="container">
		<div class="row">
			<h3>Novo post</h3>
			<form name="form" method="post" action="/posts/store">
				<div class="form-group">
					<label for="titulo">Título</label>
					<input type="text" class="form-control" id="titulo" name="titulo" placeholder="Digite o título">
				</div>
				<div class="form-group">
					<label for="conteudo">Conteúdo</label>
					<textarea class="form-control" id="conteudo" name="conteudo"></textarea>
				</div>
				<button type="submit" class="btn btn-default">Enviar</button>
			</form>
		</div>
	</div>
<?php include __DIR__ . '/../footer.html' ?>
