<?php include __DIR__ . '/../header.html' ?>
	<div class="container">
		<div class="row">
			<h3>Editar post</h3>
			<form name="form" method="post" action="<?php echo "/posts/{$post->getId()}/update"; ?>">
				<div class="form-group">
					<label for="titulo">Título</label>
					<input type="text" class="form-control" id="titulo" name="titulo" placeholder="Digite o título" value="<?php echo $post->getTitulo(); ?>">
				</div>
				<div class="form-group">
					<label for="conteudo">Conteúdo</label>
					<textarea class="form-control" id="conteudo" name="conteudo"><?php echo $post->getConteudo(); ?></textarea>
				</div>
				<button type="submit" class="btn btn-default">Enviar</button>
			</form>
		</div>
	</div>
<?php include __DIR__ . '/../footer.html' ?>
