<?php include __DIR__ . '/../header.html' ?>
	<div class="container">
		<div class="row">
			<h3>Nova categoria</h3>
			<form name="form" method="post" action="/categories/store">
				<div class="form-group">
					<label for="nome">Nome</label>
					<input type="text" class="form-control" id="nome" name="nome" placeholder="Digite o nome">
				</div>
				<button type="submit" class="btn btn-default">Enviar</button>
			</form>
		</div>
	</div>
<?php include __DIR__ . '/../footer.html' ?>
