<?php include __DIR__ . '/../templates/header.html' ?>
	<div class="container">
		<div class="row">
			<h2>POSTS</h2>
			<div class="col-md-10">
				<ul class="list-unstyled">
					<?php foreach ($posts as $post): ?>
						<li>
							<div class="jumbotron">
								<h1><?php echo $post->getTitulo(); ?></h1>
								<p><?php echo substr($post->getConteudo(), 0, 20); ?>...</p>
								<p><a class="btn btn-primary btn-lg" href="#" role="button">Leia mais</a></p>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
			<div class="col-md-2">
				<ul class="list-unstyled">
					<?php foreach ($categories as $category): ?>
						<li class="list-group-item">
							<a href="<?php echo "/?search={$category->getId()}"; ?>"><?php echo $category->getNome(); ?></a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
<?php include __DIR__ . '/../templates/footer.html' ?>
